// <auto-generated />
using Kutup.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kutup.Data.Migrations
{
    [DbContext(typeof(KutupDbContext))]
    partial class KutupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Kutup.Core.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("ISBN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishingYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.DataImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataImportType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemImport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nodes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataImports");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.DataImportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataImportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorLogs")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataImportId");

                    b.ToTable("DataImportHistories");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.DataImportMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataImportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Formula")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataImportId");

                    b.ToTable("DataImportMappings");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.Book", b =>
                {
                    b.HasOne("Kutup.Core.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutup.Core.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.DataImportHistory", b =>
                {
                    b.HasOne("Kutup.Core.Domain.Entities.DataImport", "DataImport")
                        .WithMany("DataImportHistories")
                        .HasForeignKey("DataImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataImport");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.DataImportMapping", b =>
                {
                    b.HasOne("Kutup.Core.Domain.Entities.DataImport", "DataImport")
                        .WithMany("DataImportMappings")
                        .HasForeignKey("DataImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataImport");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Kutup.Core.Domain.Entities.DataImport", b =>
                {
                    b.Navigation("DataImportHistories");

                    b.Navigation("DataImportMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
